### PR TITLE
Create setup1.md

### PR DESCRIPTION
**Pull request by omeshd**

### CODE REVIEW

**Comment by adam123woaks** [comment]
I think this is need more changes

**Comment by omeshd** [comment]
@adam123woaks I don't think we need more information

**Review by omeshd — COMMENTED** [review]
looks good

**Comment by omeshd** [comment]
> I think this is need more changes

I don't we have any changes left

**Comment by adam123woaks** [comment]
> > I think this is need more changes
> 
> I don't we have any changes left

May be you can add some docker commands here

**Comment by adam123woaks** [comment]
@omeshd Hi

**Comment by adam123woaks** [comment]
@omeshd hello

**Pull request merged**
